### ISSUE TITLE
2A03 demo Shadow of the Ninja Stage 1 title overflow

### ISSUE THREAD

**Issue by Gumball2415** [zeta0134/bhop#17]
The demo entry has an unusually long title which the graphics routine barely clears:

https://github.com/zeta0134/bhop/blob/30bb314e298ae6c897558d7682e1fc5ba519319e/demos/2a03/prg/main.s#L84

The loosely enforced 28 character limit is broken on this title, which has *29* instead, leaving a floating `1` character at the edge of the screen.

This floating character is only cleared when printing the title for `song_smb` or `song_yakra`, whose cursor overwrites and successfully clears the floating `1`, due to being 28 characters in length and the cursor being one tile ahead of the title.

**Comment by TheRealQuantam** [comment]
Dang ninjas.
