### ISSUE TITLE
Pitch Slides: Clamp to edges

### ISSUE THREAD

**Issue by zeta0134** [zeta0134/bhop#3]
A discrepancy was pointed out between Dn-FamiTracker's native playback of pitch slides, and both its NSF module and bhop's implementation. Pitch slides _should_ clamp to the edges of the range; that is, on 2A03, a positive pitch slide should not exceed a period of 2047, and a negative pitch slide should not fall below a period of 0.

Attached is a test module provided by Persune. This uses the Pxx effect on a high B-7, and to my knowledge _should_ be silent, as the Pxx effect puts the final pitch into the muting range for the pulse hardware.
[pitch_overflow_underflow_debug.dnm.zip](https://github.com/zeta0134/bhop/files/9277108/pitch_overflow_underflow_debug.dnm.zip)

**Comment by Gumball2415** [comment]
same goes with playing a `A-0` note on the 2A03 pulse with a `P71` effect

**Comment by Gumball2415** [comment]
1xx and 2xx are also observed to not clamp pitch properly
